INSERT INTO roles(role_id,role) VALUES (1,'ADMIN')
INSERT INTO roles(role_id,role) VALUES (2,'PROFESSOR')
INSERT INTO roles(role_id,role) VALUES (3,'ALUNO')

INSERT INTO periodo(id,nome) VALUES (1,'1° ANO "A"')
INSERT INTO periodo(id,nome) VALUES (2,'1° ANO "B"')
INSERT INTO periodo(id,nome) VALUES (3,'2° ANO "A"')
INSERT INTO periodo(id,nome) VALUES (4,'2° ANO "B"')
INSERT INTO periodo(id,nome) VALUES (5,'3° ANO "A"')
INSERT INTO periodo(id,nome) VALUES (6,'3° ANO "B"')
INSERT INTO periodo(id,nome) VALUES (7,'4° ANO "A"')
INSERT INTO periodo(id,nome) VALUES (8,'4° ANO "B"')
INSERT INTO periodo(id,nome) VALUES (9,'5° ANO "A"')
INSERT INTO periodo(id,nome) VALUES (10,'5° ANO "B"')
INSERT INTO periodo(id,nome) VALUES (11,'6° ANO "A"')
INSERT INTO periodo(id,nome) VALUES (12,'6° ANO "B"')
INSERT INTO periodo(id,nome) VALUES (13,'7° ANO "A"')
INSERT INTO periodo(id,nome) VALUES (14,'8° ANO "B"')
INSERT INTO periodo(id,nome) VALUES (15,'9° ANO "A"')
INSERT INTO periodo(id,nome) VALUES (16,'9° ANO "B"')
